### ISSUE TITLE
Contributors list is not updated 

### ISSUE THREAD

**Issue by imskr** [chatwoot/chatwoot-contributors#3]
I have 2 merged commits in chatwoot repo and I can't find myself in the list 

cc @fayazara

**Comment by imskr** [comment]
cc @pranavrajs

**Comment by pranavrajs** [comment]
@vishnu-narayanan Can you please check why the publish gh pages workflow is not running?

**Comment by vishnu-narayanan** [comment]
Re-opening as this issue still persists.
